### ISSUE TITLE
Cash Management

### ISSUE THREAD

**Issue by newip** [BUPT/magic-mirror#10]
Cash Management
1. Using the wechat ID: XinRobot
2. Start date: 2019/7/26
3. All consume record should be noted clearly.
4. All income record should be noted clearly.
5. We do the monthly summary for the account details.
6. The notification would be sent before cash in and out. Especially for cash out. @Huan and @Zhengyuan are the approvers as required.

R & R
1. Xin is the cash management owner for in and out.
2. Huan & Xin & Zhengyuan & LinBo is the approver for the purchase decision.

Report Duration: Monthly, Sent before the end day of each month. 

As the initial funding:
1. Huan & Xin put USD360 into AMC open-collective account. 
2. To active the cash/funding management, Huan & Xin put RMB27520 into wechat account: XinRobot.

The start date: 2019/7/23 9:00

**Comment by newip** [comment]
Huan & Xin put USD360 into AMC open-collective account.
-----------------------------------Done, 201907
To active the cash/funding management, Huan & Xin put RMB27520 into wechat account: XinRobot.
-----------------------------------Done, 20190723

**Comment by newip** [comment]
Special Remark：
The two USD360+RMB27250 from Huan and Xin were counted as lending money to kick off AMC funding management and MM project. When AMC has sufficient funding to develop itself. This money will return to Huan and Xin. Still, AMC may keep it when there is no sufficient funding to make the return.

**Comment by huan** [comment]
Thanks for keep the issues cleaning!
