### ISSUE TITLE
需要志愿者采购定向麦克风和前排对准观众的摄像头

### ISSUE THREAD

**Issue by newip** [BUPT/magic-mirror#14]

**Comment by huan** [comment]
这个 168 型号的定向麦克风，是我之前在淘宝上看到的可以做为候选： [168](https://item.taobao.com/item.htm?spm=a1z0k.7386009.0.d4919233.8158369dMnReEx&id=539690572829&_u=t2dmg8j26111)

![image](https://user-images.githubusercontent.com/1361891/62890079-42242880-bd75-11e9-9625-8920809baa50.png)

**Comment by newip** [comment]
Done by Zhenggang as HW leader.
