### ISSUE TITLE
Permission to BUPT/magic-mirror.git denied to CyFeng16.

### ISSUE THREAD

**Issue by CyFeng16** [BUPT/magic-mirror#3]
@huan 
When I was about to update some records, I got a ERROR about "ERROR: Permission to BUPT/magic-mirror.git denied to CyFeng16. fatal: 无法读取远程仓库。".
How to get access to this repo as well as I had become a contributoe of this repo, is there something wrong ? I am totally confused @_@. Look forward to you reply. Thx.

**Comment by huan** [comment]
What did you do when you get this error message?

**Comment by CyFeng16** [comment]
Got it! Thanks.
