### ISSUE TITLE
Task System Kick off Meeting

### ISSUE THREAD

**Issue by huan** [BUPT/magic-mirror#5]
Hi, @CyFeng16 and task team members:

Let's schedule a kick off meeting for the project, the goal will be:

1. Understanding the goal of the magic-mirror project
1. Understanding the goal of the sub system: task management
1. Understanding who can do what for our team
1. Setup a weekly schedule meeting for our project in the coming term

For better understanding the problem, please prepare a lightning talk slide(use google docs if possible) to introduce yourself and what you can contribute to this project before the meeting.

The lightning talk slide should include the following topics:

1. **Front cover**
1. **Introduce yourself**, for example: what is your expertise, why you join and what do you want.
1. **Magic Mirror**, for example: why we need it? why do we want to build it? what problem can it solve for us?
1. **Sub System**, what is the sub system for? describe it in detail and make sure everyone can understand your description.
1. **Your Plan**, for example, what you want to do in the coming term
1. **Back cover**

Please also make sure you had read my [idea slide about the magic mirror](https://docs.google.com/presentation/d/12I5k_lhlEyipIdHq270JzEFA8WH5B4VPZKnmjj1YHJs) before you write your slide.

Please post the google docs links to the reply of this issue before the new term begin, so that we could schedule the meeting at the beginning of the new term.

@CyFeng16 please let me know when you are ready.

**Comment by huan** [comment]
@CyFeng16 I had added you to the @BUPT/magic-mirror team, please check your email and accept it so that we could add our all team members later.

**Comment by CyFeng16** [comment]
@huan Done. Am I going to invite other team-players ?

**Comment by huan** [comment]
We had published the official announcement from our website: [Magic Mirror Project Introduction and Kick-Off Notification](https://ai-ml.club/projects/magic-mirror-introduction-and-kick-off/), this issue can be closed.

**Comment by CyFeng16** [comment]
a huge step forward! congrats!
