### ISSUE TITLE
Apply the permission of using Room 821 with the project proposal.

### ISSUE THREAD

**Issue by newip** [BUPT/magic-mirror#7]
Apply the permission of using Room 821 with the project proposal.

**Comment by newip** [comment]
[智能会议室项目申请书v2.docx](https://github.com/BUPT/magic-mirror/files/3385230/v2.docx)

**Comment by huan** [comment]
@newip The project plan is perfect. Could we convert this word document to markdown, and then publish it to our ai-ml.club website as a blog post? Because that would be easier to read, and we can keep improving it via Github.

**Comment by newip** [comment]
Give me some time. I need Zhengyuan's support. Why I can't AT him here?....

**Comment by huan** [comment]
No problem, please take your time.

Thank you very much!

**Comment by huan** [comment]
@newip It would be great if we could publish the MM project as blog post before we finishing Season 2 this weekend! :)

**Comment by newip** [comment]
.....  md文件有了，还没搞清如何post blog...

**Comment by huan** [comment]
Glad to hear that you had already finished your markdown blog file!

To post blog is very easy, please learn from the repository and you will find out how to do it very soon.

Looking forward to your MM project introduction blog, it will be the most important milestone of our MM project, thanks!

**Comment by newip** [comment]
https://github.com/BUPT/ai-ml.club/blob/master/docs/_posts/2019-07-14-magic-mirror-project-introduction-and-kick-off-notification.md

**Comment by huan** [comment]
Good job!
