### ISSUE TITLE
Project team member access right grant.

### ISSUE THREAD

**Issue by newip** [BUPT/magic-mirror#8]
@huan sir, please help to grant the access of team resources and project tab to ZhengYuan, LinBo, ZhengGang, ChenYun, ... 
Thanks.

**Comment by huan** [comment]
@newip Yes sir.

I had followed your request and added @824zzy @linbo0518 @ArronHZG to the @BUPT/magic-mirror team so that they could be able to maintain the Project now.

And, who is ChenYun? Please let me know his GitHub username, I'll add him after I got his username as well.

**Comment by newip** [comment]
> @newip Yes sir.
> 
> I had followed your request and added @824zzy @linbo0518 @ArronHZG to the @BUPT/magic-mirror team so that they could be able to maintain the Project now.
> 
> And, who is ChenYun? Please let me know his GitHub username, I'll add him after I got his username as well.

Chen Guang......

**Comment by huan** [comment]
Done.

I had added @cgpeter96  to the team, and you can maintain the team members by visit @BUPT/magic-mirror too.
